### PR TITLE
Fix: Race Condition resolved with I18n files on server starts.

### LINKED ISSUE #1585: Race condition between file reset and i18n initialization [🐛]
# :bug: Bug report

## Description

The function `lib/startup/restoreOverwrittenFilesWithOriginals` (called in `server.js` early on) copies the i18n locale files into the folder `/i18n` where they are expected to exist by the `i18n.configure` call (later in `server.js`) or later, particularly when it tries to do auto-reloading whenever a locale file changes, which might be triggered by the still ongoing copy job.

Smells like a race condition. Affects test runs frequently but also regular server starts sometimes.

### Is this a regression?

Present since i18n with auto-reloading was introduced, but it seems to occur more often recently.

### PR DESCRIPTION
**Pull request by adityaofficial10**
Fixes #1585 
What does this PR do?
This PR fixes issue #1585 to resolve the race condition between file reset and configuration of i18n files.

Steps taken:
Two asynchronous functions configureI18n() and reloadI18nFiles() have been added to ensure that the file copying process finishes before configuring I18n.
fix

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -114,10 +114,14 @@ const collectDurationPromise = (name, func) => {
   }
 }
 collectDurationPromise('validatePreconditions', require('./lib/startup/validatePreconditions'))()
-collectDurationPromise('restoreOverwrittenFilesWithOriginals', require('./lib/startup/restoreOverwrittenFilesWithOriginals'))()
 collectDurationPromise('cleanupFtpFolder', require('./lib/startup/cleanupFtpFolder'))()
 collectDurationPromise('validateConfig', require('./lib/startup/validateConfig'))()
 
+// Reloads the i18n files in case of server restarts or starts.
+async function reloadI18nFiles () {
```
Comment (J12934) [inline server.js]: I think it would be better just name this wrapper function `restoreOverwrittenFilesWithOriginals`, otherwise there are two names for this functionality.

File: server.js [hunk 2]
```diff
@@ -114,10 +114,14 @@ const collectDurationPromise = (name, func) => {
...
+  collectDurationPromise('restoreOverwrittenFilesWithOriginals', require('./lib/startup/restoreOverwrittenFilesWithOriginals'))()
```
Comment (J12934) [inline server.js]: This needs to be awaited. Otherwise we'd still have the race condition

```suggestion
  await collectDurationPromise('restoreOverwrittenFilesWithOriginals', require('./lib/startup/restoreOverwrittenFilesWithOriginals'))()
```

File: server.js [hunk 3]
```diff
@@ -251,14 +255,16 @@ app.use(express.static(path.join(__dirname, '/frontend/dist/frontend')))
...
 /* Configure and enable backend-side i18n */
-i18n.configure({
-  locales: locales.map(locale => locale.key),
-  directory: path.join(__dirname, '/i18n'),
-  cookie: 'language',
-  defaultLocale: 'en',
-  autoReload: true
-})
-app.use(i18n.init)
+async function configureI18n () {
```
Comment (J12934) [inline server.js]: This function doesn't need to be async.

**Review by J12934 — CHANGES_REQUESTED** [review]
Looks good 👍
But requires some further tweeks

**Comment by adityaofficial10** [comment]
@J12934 
Thanks for reviewing..
I'll make the necessary changes and commit here..

**Review by bkimminich — CHANGES_REQUESTED** [review]
I ran `npm frisby` and ended up with every `500` errors instead of expected `200`s. When I `npm start`ed the server and browsed to the main page, I get these errors in the console:

```
TypeError: req.__ is not a function
    at C:\Data\GitHub\juice-shop\routes\search.js:52:34
TypeError: req.__ is not a function
    at List.<anonymous> (C:\Data\GitHub\juice-shop\server.js:463:49)
    at runHookFunction (C:\Data\GitHub\juice-shop\node_modules\finale-rest\lib\Controllers\base.js:147:44)
    at tryCatcher (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
info: Solved 1-star errorHandlingChallenge (Error Handling)
info: Cheat score for trivial errorHandlingChallenge solved in 0 / 0 minutes with hints allowed: 0
TypeError: req.__ is not a function
    at List.<anonymous> (C:\Data\GitHub\juice-shop\server.js:463:49)
    at runHookFunction (C:\Data\GitHub\juice-shop\node_modules\finale-rest\lib\Controllers\base.js:147:44)
    at tryCatcher (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```

image

The `req.__` function that is missing is the one which `i18n` adds to all requests for access to translations. I suppose the initialization did not complete. Btw, I was waiting for like 10sec after restart before requesting the page, so the server had enough time to complete everything.

**Comment by adityaofficial10** [comment]
@bkimminich 
I'll go through the code again and do the needful.
Thanks.

**Comment by adityaofficial10** [comment]
@bkimminich 
Can you tell me what purpose does that portion of code serve?
I think we'll have to wrap that up in a separate async function so that it occurs after i18n is configured.
So to name the function, I'll need the purpose.

File: server.js (hunk 3 above)
Comment (adityaofficial10) [reply server.js]: @J12934 
I just made that async so as to ensure that it executes after reloading has finished..

**Comment by bkimminich** [comment]
That code is part of the `i18n` module, not of Juice Shop. We just use this as a feature. I guess wrapping the configuration of i18n into async had some side effect with Express. But your guess is as good as mine here.

File: server.js (hunk 3 above)
Comment (J12934) [reply server.js]: Okay but this has nothing to do with the order.
That is ensured by the `await` in the `await reloadI18nFiles()` statement.

This ensures that the following statements only run after the promise it returns are completed, no matter if these functions are async or not.

**Comment by adityaofficial10** [comment]
@J12934 
I've changed the function name and its nature as instructed.
@bkimminich 
As for the approach, I tried using then() and it works perfectly.
I ran the tests locally and they passed.
So is this fine now?
Screenshot 2021-02-23 at 1 35 45 AM

**Comment by bkimminich** [comment]
Just tried it locally and so far works fine. I've merged latest `develop` back into your fork and will merge the PR if CI/CD passed. Thanks a lot!

PS: If you send me your post address I'll send you a few stickers as a _thank you!_ for your first merged PR!

**Comment by adityaofficial10** [comment]
@bkimminich 
Thanks a lot for that.
I'd also like to discuss this OWASP GSoC idea related to juice shop.
So Can I contact you directly for the same or through the mailing lists?

**Comment by bkimminich** [comment]
You can write me an email or DM me on Slack or Gitter, sure!

**Comment by adityaofficial10** [comment]
Great!
Thanks a lot..
I'll analyse the idea a bit more and reach out to you..
